// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJxsKVFlwaRSR51qsFXDGld1lea610Cg',
    appId: '1:54473355441:web:37761407387187039db290',
    messagingSenderId: '54473355441',
    projectId: 'medinexa-cf258',
    authDomain: 'medinexa-cf258.firebaseapp.com',
    storageBucket: 'medinexa-cf258.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-57iKIHRcjtYPPC5n4KQyibaXuZY1SYk',
    appId: '1:54473355441:android:47ae847c5d0ccb069db290',
    messagingSenderId: '54473355441',
    projectId: 'medinexa-cf258',
    storageBucket: 'medinexa-cf258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDZGG-3j_KtzvT0_XewwvScj8BFZQYAU',
    appId: '1:54473355441:ios:a81c25c195520e059db290',
    messagingSenderId: '54473355441',
    projectId: 'medinexa-cf258',
    storageBucket: 'medinexa-cf258.firebasestorage.app',
    iosClientId: '54473355441-u0f7eajtqs0n3dueusdisuar1og67043.apps.googleusercontent.com',
    iosBundleId: 'com.medinexa.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFDZGG-3j_KtzvT0_XewwvScj8BFZQYAU',
    appId: '1:54473355441:ios:a81c25c195520e059db290',
    messagingSenderId: '54473355441',
    projectId: 'medinexa-cf258',
    storageBucket: 'medinexa-cf258.firebasestorage.app',
    iosClientId: '54473355441-u0f7eajtqs0n3dueusdisuar1og67043.apps.googleusercontent.com',
    iosBundleId: 'com.medinexa.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJxsKVFlwaRSR51qsFXDGld1lea610Cg',
    appId: '1:54473355441:web:e703aa50f56b802d9db290',
    messagingSenderId: '54473355441',
    projectId: 'medinexa-cf258',
    authDomain: 'medinexa-cf258.firebaseapp.com',
    storageBucket: 'medinexa-cf258.firebasestorage.app',
  );
}
